### ISSUE TITLE
Adding a license to the repository

### ISSUE THREAD

**Issue by dimarash-hub** [pereira-gha/activefire#11]
Thank you for the research and publishing the data and weights, this is highly appreciated!
Could you consider adding a license to the repo so that the resources published can be used officially?

**Comment by Minoro** [comment]
Hello,
I'm glad about your interest in our project.
I'll ask the others about a specific license, but feel free to use this project as long you cite it.
If you want to use something from the article you can use the [copyright tool from Elsevier.](https://s100.copyright.com/App/checkLoginCas.jsp?service=https%3A%2F%2Fs100.copyright.com%2FAppDispatchServlet%3FpublisherName%3DELS%26contentID%3DS092427162100160X%26orderBeanReset%3Dtrue)

**Comment by dimarash-hub** [comment]
Great! Thank you very much

**Comment by Minoro** [comment]
Hello,
I'm sorry for the late response.
After some consideration, the team decides that the [CC-BY 4.0 Licence](https://creativecommons.org/licenses/by/4.0/)

We have added this information to the README.
