### ISSUE TITLE
How to download H5 files?

### ISSUE THREAD

**Issue by zhouyiks** [pereira-gha/activefire#3]
Dear Author, I read this paper and want to test this model on my small Sentinel-2 dataset. However, I  failed to download these H5 weights files. There are some warnings like that "This repository is over its data quota." when I use git Bash and LFS to download these files. Is there other ways to download these weight files?

**Comment by zhouyiks** [comment]
Or you can upload these data to Google Drive, is it possible?

**Comment by zhouyiks** [comment]
Or could send me the single weight file "voting/unet_16f_2conv_762/train_output/model_unet_Voting_final_weights.h5" to my Google Email: zyk4334@gmail.com
please, I really need it

**Comment by Minoro** [comment]
We just updated our repository and added some scripts to help anyone who want to download the weights. Inside the `src/utils` directory you can run: 
```
python download_weights.py
python unzip_download_weights.py
```
