### ISSUE TITLE
Is there a way to know the bands you are using?

### ISSUE THREAD

**Issue by farhan-shakib** [pereira-gha/activefire#5]
Hello! I could not find the band information in your readme.md file. So I wanted to ask here.

**Comment by Minoro** [comment]
Hello,
The models that use only three channels use the bands 7, 6 and 2.
The models that use 10 channels don't use the band 8.
I hope this information helps you.

**Comment by farhan-shakib** [comment]
By 7, 6, 2 you mean **SWIR2**, **SWIR1** and **Blue**?

**Comment by Minoro** [comment]
Yes.

**Comment by farhan-shakib** [comment]
@Minoro  Thanks a lot.
