### ISSUE TITLE
how to get coordinates (longitude latitude) of output image?

### ISSUE THREAD

**Issue by thylm** [pereira-gha/activefire#9]
I found that images in dataset (include source images and marks) have  geography coordinates  but the output images don't 

I would like to get geography coordinates of output images to show on the map

thank you

**Comment by Minoro** [comment]
Hi,

The output image has the same coordinates as the input image.
This means that the pixel at position (x,y) in the output image corresponds to the same position as in the input image.

You can save the output image with the same "transform" and "CRS" metadata used in the input image. 

Something like this should do the trick:
```python
with rasterio.open(IMAGE_PATH) as src:
    input_meta = src.meta
   # Your code to generate the output...

output_meta = input_meta.copy()
output_meta.update(count=1) # <- Notice that you may need to update the number of output channels
with rasterio.open('output.tif', 'w+', **output_meta) as dst:
    dst.write_band(1, np.asarray(y_pred*255, dtype=np.uint16))
```

**Comment by thylm** [comment]
thank you for your response
and I have found an easier way to attach "transform" and "CRS" metadata from input image to output image 

like this:

```
with rasterio.open(IMAGE_PATH) as src:
    input_meta = src.meta

with rasterio.open('output.tif', 'w+', **output_meta) as dst:
    dst.crs = input_meta['crs']
    dst.transform = input_meta['transform']
    
```

**Comment by thylm** [comment]
Thank you for the information

I have found an easier way to attach "transform" and "CRS" metadata from input image to output image

like this:
with rasterio.open(IMAGE_PATH) as src:
    input_meta = src.meta

with rasterio.open('output.tif', 'r+') as dst:
    dst.crs = input_meta['crs']
    dst.transform = input_meta['transform']

**Comment by thylm** [comment]
Thank you for the information

I have found an easier way to attach "transform" and "CRS" metadata from input image to output image:

```
with rasterio.open(IMAGE_PATH) as src:
    input_meta = src.meta

with rasterio.open('output.tif', 'r+') as dst:
    dst.crs = input_meta['crs']
    dst.transform = input_meta['transform']
```

hopefully, it is useful

**Comment by Minoro** [comment]
Hi, I'm glad to know that you have found a solution.
If you wanna contribute to this project you can write a Jupyter Notebook with a full example.
I think it would help others facing the same problem.

**Comment by thylm** [comment]
Could you please give me a name and location of an image has fire?
the dataset has a lot of images so I  can not find the image has fire.
when I generate masks, all just have black at all

**Comment by thylm** [comment]
I found LC08_L1TP_046031_20200908_20200908_01_RT in landsat_patches in https://drive.google.com/drive/folders/1Gv96zhQ0HwIyquDL8vroarHoz_SJXtv5 but it has 692 images so I can not find the image has fire. Please help me

**Comment by thylm** [comment]
Hello, please help me how to split satellite images into grid with each sections sized 256x256? 
I want to generate patches from satellite images

**Comment by Minoro** [comment]
Hi,
The code under the directory src/landsat/create_masks.py can give you a starting point for what you want to do.
I believe that the function `get_split` does what you want.

[create_masks.py](https://github.com/pereira-gha/activefire/blob/523f03c6022f00efcfcd0a63de16f5337b1bb267/src/landsat/create_masks.py#L196)

The code mentioned uses `gdal`, but you can also use `rasterio`.
